#!/bin/bash

set -e
SCRIPT_VERSION="v2.0.0"

clear
echo
#print_brake 70
echo "* Axton's Pterodactyl Updater @ $SCRIPT_VERSION"
echo
echo "* Copyright (C) 2022."
echo "* https://github.com/axtonprice/pterodactyl-utilities"
echo
echo "* This script is not associated with the official Pterodactyl project!"
#print_brake 70
echo
echo "1. Update Panel"
echo "2. Update Wings"
echo "3. Close / Cancel"
read -p "Please enter a number: " choice
if [ $choice == "1" ]
    then
    bash <(curl -s https://raw.githubusercontent.com/finnie2006/PteroFreeStuffinstaller/V2/resources/DarkNColor.sh)
fi
if [ $choice == "2" ]
    then
    bash <(curl -s https://raw.githubusercontent.com/finnie2006/PteroFreeStuffinstaller/V2/resources/Addons.sh)
fi
if [ $choice == "3" ]
    then
    echo "Canceling..."
    exit 0
fi
